-- WK.metrics - Seed de Indicadores
-- Importação automática da planilha indicadores_eng_azuredevops_v3.xlsx
-- Total de indicadores: 51
-- Data de geração: 2025-11-15 23:54:36

-- Limpar indicadores existentes (opcional - comentar se quiser manter)
-- DELETE FROM public.indicators;

-- Inserir indicadores

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  1,
  'Lead Time (Pedido → Valor em Produção)',
  'LT',
  'Downstream',
  'Fluxo/Entrega',
  'Mensurar o tempo total desde a criação até estar disponível em produção para o cliente.',
  'Mensurar o tempo total desde a criação até estar disponível em produção para o cliente.',
  'LT = data_implantação_prod − data_criação (por item); usar mediana',
  'Fatiar histórias; limitar WIP; atacar colunas com maior espera (CFD); automatizar deploy contínuo; priorizar PR→Deploy; swarming nos bloqueios.',
  'Fluxo enxuto; lead time previsível; clientes percebem valor mais rápido; menos estoque em andamento.',
  'Definir baseline por tipo (Feature/Bug). Ex.: mediana < 5 dias (feature), < 2 dias (bug P2–P3).',
  'Sprint e Mensal /Por versão*',
  'Por Squad, Produto, Tipo de Item',
  'System.CreatedDate; Data de Deploy (Release/Deployment/Pipeline) vinculada ao Work Item',
  'OData Analytics: WorkItems (CreatedDate) + implantações via Releases/Deployments; correlacionar pelo Link WorkItem↔Release'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  2,
  'Cycle Time (Início de trabalho → Done)',
  'CT',
  'Downstream',
  'Fluxo/Entrega',
  'Tempo efetivo de execução; reduz filas e gargalos.',
  'Tempo efetivo de execução; reduz filas e gargalos.',
  'CT = data_entrada_em_‘In Progress’ − data_‘Done/Closed’ (por item); mediana',
  'Quebrar itens grandes; limitar WIP; puxar reviewers cedo; remover bloqueios; DoD objetivo; concluir antes de puxar novo item.',
  'Execução ágil; pouca fila/espera; squads concluem o que começam; menor variância entre itens.',
  'Mediana < 3 dias; P85 < 5 dias.',
  'Sprint',
  'Por Squad, Profissional',
  'WorkItemSnapshots (State, StateChangeDate)',
  'OData: WorkItemSnapshots filtrar transições para estados ativos e finalizados'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  3,
  'Frequência de Deploy',
  'DF',
  'Downstream',
  'DevOps/DORA',
  'Aumentar cadência de entrega segura.',
  'Aumentar cadência de entrega segura.',
  'DF = nº de deploys em produção por período',
  'Automatizar CD; trunk‑based; feature flags; reduzir batch size; janelas de deploy diárias com canary/blue‑green; cortar aprovações manuais desnecessárias.',
  'Entregas frequentes e pequenas; feedback rápido; menor risco por batch; menos hotfixes.',
  '≥ diário por serviço crítico; semanal para serviços de menor criticidade.',
  'Semanal e Mensal',
  'Por Serviço/Repo',
  'Pipelines/Deployments',
  'OData: Deployments agrupar por Environment=Production'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  4,
  'Taxa de Falha de Mudança',
  'CFR',
  'Downstream',
  'DevOps/DORA',
  'Mensurar estabilidade das mudanças.',
  'Mensurar estabilidade das mudanças.',
  'CFR = deploys que geraram rollback/hotfix incident ≥ P1/P2 ÷ total de deploys',
  'Endurecer quality gates; canary e rollback automático; testes de contrato; review de risco; RCA 5 porquês; ações preventivas por serviço.',
  'Releases estáveis; quase nenhum rollback; confiança do negócio cresce após cada deploy.',
  '≤ 15% (melhorar para ≤ 10%).',
  'Mensal',
  'Por Serviço/Produto',
  'Deployments; Incidents (Work Item tipo Incident)',
  'Relacionar Deployments↔Incidents em janela de 24–48h pós-deploy'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  5,
  'Tempo Médio de Recuperação',
  'MTTR',
  'Downstream',
  'DevOps/DORA',
  'Reduzir tempo de indisponibilidade percebido.',
  'Reduzir tempo de indisponibilidade percebido.',
  'MTTR = média(tempo entre abertura do incidente e restauração do serviço)',
  'Observabilidade (logs, métricas, tracing); alertas acionáveis; runbooks; on‑call claro; feature toggles; simular incidentes (gamedays).',
  'Incidentes resolvidos rapidamente; impacto reduzido; SLOs atendidos; confiança operacional alta.',
  '< 60 min para P1; < 4h para P2.',
  'Mensal e por incidente',
  'Por Serviço/Componente',
  'Work Items tipo Incident/Problem; timestamps de status',
  'OData: IncidentWorkItems (CreatedDate, ResolvedDate)'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  6,
  'Throughput (Itens Concluídos)',
  'TP',
  'Downstream',
  'Fluxo',
  'Capacidade de entrega; input p/ forecasting.',
  'Capacidade de entrega; input p/ forecasting.',
  'TP = nº de itens concluídos por período',
  'Nivelar capacidade; reduzir interrupções; priorizar finalizações; refinar backlog; revisar WIP limit; balancear dev/QA.',
  'Capacidade estável; tendência previsível para forecast; sem picos artificiais.',
  'Estabilizar variação ≤ 20% por sprint.',
  'Sprint',
  'Por Squad, Tipo (Feature/Bug/Task)',
  'WorkItems State=Done/Closed',
  'WIQL: SELECT ... WHERE [State] IN (''Done'',''Closed'') AND [IterationPath]=@CurrentIteration'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  7,
  'Confiabilidade de Compromisso (Planned→Done)',
  'CR%',
  'Downstream',
  'Planejamento',
  'Disciplina de planejamento e foco.',
  'Disciplina de planejamento e foco.',
  'CR% = concluído comprometido ÷ comprometido no início da sprint',
  'Melhorar planning; buffer para imprevistos; controlar scope creep; negociar interrupções; foco no comprometido.',
  'Planejamento confiável; menos promessa quebrada; stakeholders com expectativas ajustadas.',
  '≥ 85% sustentado (com baixa variação).',
  'Sprint',
  'Por Squad',
  'Itens no plano da Sprint (Iteration backlog)',
  'Capturar ‘scope at start’ via snapshot/marker de sprint; comparar com concluído'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  8,
  'Eficiência de Fluxo',
  'FE%',
  'Downstream',
  'Fluxo/Lean',
  'Identificar gargalos e filas.',
  'Identificar gargalos e filas.',
  'FE% = tempo_em_trabalho_ativo ÷ tempo_total_do_ciclo',
  'Eliminar esperas/handoffs; balancear QA/dev; automatizar tarefas; pareamento nas filas; explicitar políticas de fluxo.',
  'Pouca espera entre etapas; gargalos visíveis e raros; sensação de fluidez no quadro.',
  'Elevar gradualmente para > 40%.',
  'Mensal',
  'Por Squad',
  'Transições de coluna Kanban (Analytics)',
  'WorkItemSnapshots por coluna/estado (Active vs Waiting)'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  9,
  'WIP por Desenvolvedor',
  'WIP/Dev',
  'Downstream',
  'Fluxo/Capacidade',
  'Reduzir multitarefa e aumentar foco.',
  'Reduzir multitarefa e aumentar foco.',
  'WIP/Dev = itens em progresso ÷ nº de devs ativos',
  'Aplicar WIP limit por pessoa; ‘stop starting, start finishing’; daily de desbloqueio; reduzir multitarefa.',
  'Baixa multitarefa; foco elevado; profissionais finalizam rápido e com qualidade.',
  '≤ 1,5 por dev; ideal ~1.',
  'Semanal',
  'Por Squad, Profissional',
  'State=''Active/In Progress''; AssignedTo',
  'WIQL: WHERE [State] IN (''Active'',''In Progress'') GROUP BY [Assigned To]'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  10,
  'Taxa de Defeitos Escapados para Produção',
  'DER',
  'Downstream',
  'Qualidade',
  'Capturar vazamento de defeitos para cliente final.',
  'Capturar vazamento de defeitos para cliente final.',
  'DER = bugs reportados por cliente (prod) ÷ bugs totais',
  'Aumentar testes (contrato/e2e); validação em staging; critérios de aceite claros; beta; feature flags.',
  'Poucos bugs chegam ao cliente; reputação protegida; custo de suporte reduzido.',
  '≤ 10%; reduzir trimestre a trimestre.',
  'Mensal',
  'Por Produto/Módulo',
  'Work Item ‘Bug’ com Tag/Área=Produção/Cliente',
  'WIQL: WHERE [Work Item Type]=''Bug'' AND [Tags] CONTAINS ''Prod'''
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  11,
  'Densidade de Defeitos',
  'DD',
  'Downstream',
  'Qualidade',
  'Normalizar defeitos por volume de entrega.',
  'Normalizar defeitos por volume de entrega.',
  'DD = nº bugs ÷ (100 itens entregues ou 1000 LOC)',
  'RCA por módulo; refatorar hotspots; reforçar DoR; revisão técnica; fortalecer testes no módulo crítico.',
  'Defeitos proporcionais ao volume; tendência de queda em módulos críticos; qualidade crescente.',
  'Queda contínua; metas por módulo.',
  'Mensal',
  'Por Squad, Produto',
  'Bugs; throughput; (LOC via repositório opcional)',
  'OData: Bugs fechados no período ÷ Itens entregues'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  12,
  'Taxa de Reabertura de Itens',
  'RR',
  'Downstream',
  'Qualidade',
  'Sinaliza qualidade de validação e definição.',
  'Sinaliza qualidade de validação e definição.',
  'RR = itens reabertos ÷ itens concluídos',
  'Refinar critérios de aceite; checklist de validação; QA em pareamento; testes antes do ‘Done’; revisão funcional.',
  'Pouca reabertura; aceitação na primeira; definição/validação funcionam bem.',
  '≤ 5%.',
  'Mensal',
  'Por Squad, Profissional',
  'WorkItemHistory (state re-open transitions)',
  'Snapshots detectando transição Done→Active'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  13,
  'Idade de Bugs Abertos (Mediana)',
  'BA',
  'Downstream',
  'Qualidade/Suporte',
  'Evitar estoque crônico de defeitos.',
  'Evitar estoque crônico de defeitos.',
  'BA = mediana(hoje − data_criação) dos bugs abertos',
  'Mutirão de bugs; SLO por severidade; política de não iniciar novas features até reduzir estoque; priorizar por impacto.',
  'Backlog de bugs saudável; sem ‘casos antigos’; equipe ataca problemas com cadência.',
  'Mediana < 7 dias; P90 < 21 dias.',
  'Semanal',
  'Por Severidade/Produto',
  'Work Items tipo Bug (State != Closed)',
  'WIQL: WHERE [Work Item Type]=''Bug'' AND [State] NOT IN (''Closed'',''Done'')'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  14,
  'Mix de Severidade de Bugs',
  'SMix',
  'Downstream',
  'Qualidade',
  'Entender impacto e tendência de severidades.',
  'Entender impacto e tendência de severidades.',
  '% por severidade (P1/P2/P3/… ) no período',
  'Squad dedicado a P1/P2; hardening sprint; reforçar testes; regressão; monitoramento de erros.',
  'Quase inexistem P1; P2 sob controle; risco operacional reduzido.',
  'P1 ≤ 5% dos bugs; P2 ≤ 20%.',
  'Mensal',
  'Por Produto/Módulo',
  'Campo Severity/Tags customizados',
  'Distribuição por campo Severity'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  15,
  'Tempo de Review de PR (Mediana)',
  'CRT',
  'Downstream',
  'Qualidade/Fluxo',
  'Acelerar feedback e reduzir filas.',
  'Acelerar feedback e reduzir filas.',
  'CRT = mediana(data_merge − data_criação_PR)',
  'SLA de review (<8h); rotação de revisores; evitar PRs grandes; janela diária de review; notifications.',
  'Feedback de PR rápido; fila de review anda; menos bloqueio pós-merge.',
  '< 8h úteis; P85 < 24h.',
  'Semanal',
  'Por Repo, Revisor',
  'Pull Requests (PRs)',
  'OData: PullRequests with ClosedDate−CreationDate'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  16,
  'Tamanho de PR (Mediana de linhas alteradas)',
  'PRS',
  'Downstream',
  'Qualidade',
  'PRs menores são mais fáceis de revisar.',
  'PRs menores são mais fáceis de revisar.',
  'linhas_adicionadas+removidas (mediana)',
  'Quebrar PRs; trunk‑based; toggles; limites por repo; treinar diffs pequenos e focados.',
  'PRs pequenos; revisão fácil; menor risco de regressão; merges contínuos.',
  'Mediana < 300 linhas; P90 < 800.',
  'Semanal',
  'Por Repo',
  'PRs (stats de diff)',
  'Repos PRs diffs via API/Analytics'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  17,
  'Cobertura de Review (% PRs revisados por ≥2)',
  'RCOV%',
  'Downstream',
  'Qualidade/Processo',
  'Garantir revisão colaborativa.',
  'Garantir revisão colaborativa.',
  'PRs com ≥2 revisores ÷ PRs merged',
  'Exigir ≥2 revisores em serviços críticos; checklists; rotação; pairing em mudanças sensíveis.',
  'Revisão colaborativa; difusão de conhecimento; menos falhas não detectadas.',
  '≥ 80%.',
  'Mensal',
  'Por Repo, Squad',
  'PR reviewers',
  'PullRequests + Reviewers'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  18,
  'Taxa de Sucesso de Build',
  'BSR',
  'Downstream',
  'CI/CD',
  'Estabilidade do pipeline.',
  'Estabilidade do pipeline.',
  'BSR = builds succeeded ÷ builds totais',
  'Corrigir testes/ambiente; isolar flaky; cache; paralelismo; health de agentes; falha rápida.',
  'Pipelines estáveis; raras falhas de infraestrutura; tempo dos devs poupado.',
  '> 95%.',
  'Semanal',
  'Por Pipeline',
  'Builds (Status)',
  'OData: Builds group by Result'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  19,
  'Duração do Pipeline (Mediana)',
  'PD',
  'Downstream',
  'CI/CD',
  'Feedback rápido para devs.',
  'Feedback rápido para devs.',
  'PD = mediana(Completed − Started)',
  'Paralelizar; cache dependências; split de suites; testes críticos primeiro; otimizar containers.',
  'Feedback rápido na CI/CD; iterações curtas; evita filas de build/test.',
  '< 10 minutos CI; < 20 min CD.',
  'Semanal',
  'Por Pipeline',
  'Builds/Releases',
  'OData: Builds durations'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  20,
  'Taxa de Testes Instáveis (Flaky)',
  'FTR',
  'Downstream',
  'Qualidade/Testes',
  'Reduz falsos negativos e desperdício.',
  'Reduz falsos negativos e desperdício.',
  'FTR = testes com resultados inconsistentes ÷ testes executados',
  'Quarentena de flaky; triagem semanal; corrigir ou remover; ownership do módulo.',
  'Testes confiáveis; menos falsos alarmes; confiança na suite de regressão.',
  '< 1%.',
  'Mensal',
  'Por Suite',
  'TestRuns/TestResults',
  'OData: TestResults; flag flaky'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  21,
  'Cobertura de Testes Automatizados',
  'TCOV%',
  'Downstream',
  'Qualidade/Testes',
  'Garantir proteção mínima do código.',
  'Garantir proteção mínima do código.',
  'TCOV% = linhas cobertas ÷ linhas executáveis',
  'Cobrir caminhos críticos; metas por serviço; gate no pipeline; evitar ‘gaming’.',
  'Cobertura protege caminhos críticos; poucas regressões; gate confiável.',
  '≥ 60% por serviço (evitar metas cegas).',
  'Mensal',
  'Por Serviço/Repo',
  'Publicar cobertura via pipeline (p.ex. Cobertura Jacoco/Lcov)',
  'Pipeline test coverage reports'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  22,
  'Índice de Dívida Técnica',
  'TDR',
  'Downstream',
  'Qualidade/Código',
  'Controlar dívida técnica.',
  'Controlar dívida técnica.',
  'TDR = esforço para corrigir problemas ÷ esforço de dev',
  'Refatorar módulos com alta dívida; hardening; quality gate ‘A’; análise estática obrigatória.',
  'Dívida técnica sob controle; qualidade de código melhora; manutenção mais barata.',
  'Redução contínua; ‘Remediation’ < 5% do esforço.',
  'Mensal',
  'Por Serviço/Repo',
  'SonarQube Publish Quality Gate (no pipeline)',
  'Extrair via API Sonar e consolidar'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  23,
  'Code Churn (Reescrita recente)',
  'CHURN%',
  'Downstream',
  'Código/Fluxo',
  'Detectar retrabalho e instabilidade.',
  'Detectar retrabalho e instabilidade.',
  'CHURN% = linhas alteradas ≤ 3 semanas após criadas ÷ linhas alteradas',
  'Revisar design; eliminar retrabalho recorrente; spikes; estabilizar requisitos; reduzir urgências.',
  'Pouco retrabalho; decisões técnicas estáveis; roadmap anda sem oscilações.',
  '< 20%.',
  'Mensal',
  'Por Repo, Dev',
  'Commits/PRs',
  'Repos Commits analytics'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  24,
  'Taxa de Retrabalho (Itens)',
  'REWORK%',
  'Downstream',
  'Processo',
  'Endereçar causas-raiz upstream.',
  'Endereçar causas-raiz upstream.',
  'REWORK% = itens marcados como retrabalho ÷ itens concluídos',
  'RCA de retrabalho; reforçar DoR; validação com usuário; prototipação; bloquear início sem aceite.',
  'Itens certos da primeira vez; desperdício baixo; menos idas e vindas.',
  '< 10%.',
  'Mensal',
  'Por Squad',
  'Tag ‘rework’ ou Work Item ‘Rework’',
  'WIQL: Tags CONTAINS ''rework'''
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  25,
  'Variação de Escopo na Sprint',
  'SC%',
  'Downstream',
  'Planejamento',
  'Proteger foco e previsibilidade.',
  'Proteger foco e previsibilidade.',
  'SC% = itens adicionados após start ÷ comprometido inicial',
  'Change control; buffer; swimlane de interrupções; negociar prioridades.',
  'Sprint focada; poucas mudanças de escopo; time cumpre combinado.',
  '≤ 15%.',
  'Sprint',
  'Por Squad',
  'Snapshot backlog de sprint',
  'Comparar backlog no dia 1 vs dia N'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  26,
  'Taxa de Itens Prontos para Desenvolvimento',
  'RRR',
  'Upstream',
  'Discovery/Backlog',
  'Garantir esteira alimentada com qualidade.',
  'Garantir esteira alimentada com qualidade.',
  'RRR = itens ‘Ready’ ÷ itens no topo do backlog (horizonte 2 sprints)',
  'Acelerar refinement; DoR claro; manter 2 sprints de itens prontos; dupla PO+Tech.',
  'Esteira sempre abastecida; time não fica ocioso nem puxa item ruim.',
  '≥ 120% da capacidade de 2 sprints.',
  'Semanal',
  'Por Produto',
  'Estado/Coluna ‘Ready’, Tags DoR',
  'WIQL: WHERE [State]=''Ready'''
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  27,
  'Conformidade à Definition of Ready',
  'DoR%',
  'Upstream',
  'Qualidade de Especificação',
  'Evita ambiguidade e retrabalho.',
  'Evita ambiguidade e retrabalho.',
  'DoR% = itens com checklist DoR ok ÷ itens movidos para ‘In Progress’',
  'Bloquear início sem DoR; checklist automático; treinar PO/analistas; auditoria amostral.',
  'Itens entram em dev prontos; menos dúvidas e interrupções; fluxo estável.',
  '≥ 95%.',
  'Mensal',
  'Por Squad/PO',
  'Campos customizados de checklist',
  'WIQL por campo booleano'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  28,
  'Índice de Qualidade de Especificação',
  'SQI',
  'Upstream',
  'Discovery/Produto',
  'Elevar clareza e completude antes do dev.',
  'Elevar clareza e completude antes do dev.',
  'Pontuação 0–5 para critérios (aceite, UX, riscos, dados); média',
  'Revisão cruzada de specs; templates; anexar UX/riscos/dados; grooming de qualidade.',
  'Especificações claras; menos ambiguidade; velocidade sem sacrificar qualidade.',
  '≥ 4,0.',
  'Mensal',
  'Por PO/Produto',
  'Campos custom ‘SpecScore’',
  'Query por campo numérico'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  29,
  'Lead Time de Análise de Arquitetura/UX',
  'DRLT',
  'Upstream',
  'Discovery/Arquitetura',
  'Garantir design ‘just in time’ sem travar execução.',
  'Garantir design ‘just in time’ sem travar execução.',
  'DRLT = aprovação_design − submissão_design',
  'SLA de análise; agenda fixa com arquitetura/UX; padrões reutilizáveis; design spikes time‑boxed.',
  'Design chega no tempo; time não fica esperando; menos bloqueios de arquitetura/UX.',
  '< 2 dias úteis.',
  'Semanal',
  'Por Arquitetura/UX',
  'Work Item ‘Enabler/Spike/Design Review’',
  'WIQL por tipo e datas'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  30,
  'Proporção Discovery/Delivery',
  'DDR',
  'Upstream',
  'Portfólio/Balanceamento',
  'Balancear aprendizado vs execução.',
  'Balancear aprendizado vs execução.',
  'DDR = esforço de discovery ÷ esforço total (por período)',
  'Rebalancear capacidade; discovery contínuo 10–20%; cortar escopo não validado; testes com usuários.',
  'Balanceamento saudável; aprendizado contínuo sem travar delivery.',
  '10–20% discovery contínuo.',
  'Mensal',
  'Por Produto',
  'Itens tipo Spike/Discovery; Effort/RemainingWork',
  'WIQL por tipos e somatórios'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  31,
  'Saúde do Backlog (Semanas de Itens Ready)',
  'BH',
  'Upstream',
  'Planejamento',
  'Evitar seca de itens prontos.',
  'Evitar seca de itens prontos.',
  'BH = (pontos prontos) ÷ (capacidade semanal)',
  'Refinar topo; estimar; remover obsoletos; manter pipeline ready 3–5 semanas.',
  'Backlog vivo e priorizado; ausência de seca; previsibilidade elevada.',
  '3–5 semanas.',
  'Semanal',
  'Por Produto',
  'Story Points; State ‘Ready’',
  'Somatório de Story Points prontos'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  32,
  'Acurácia de Estimativa (MAPE)',
  'EA%',
  'Downstream',
  'Planejamento',
  'Melhorar previsões de esforço/duração.',
  'Melhorar previsões de esforço/duração.',
  'EA% = 1 − MAPE(estimado, realizado)',
  'Post‑mortem de estimativas; usar histórico; T‑shirt size; evitar horas; melhorar slicing.',
  'Estimativas úteis para planejamento; desvios pequenos; confiança no plano.',
  '≥ 80%.',
  'Sprint',
  'Por Squad',
  'OriginalEstimate, CompletedWork, Story Points',
  'Comparar campos de esforço e realizado'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  33,
  'Utilização de Capacidade',
  'CU%',
  'Downstream',
  'Capacidade',
  'Evitar sobre/ subalocação crônica.',
  'Evitar sobre/ subalocação crônica.',
  'CU% = horas alocadas em trabalho de sprint ÷ horas disponíveis',
  'Recalibrar capacidade; retirar trabalho fora da sprint; reduzir reuniões; contratar se crônico.',
  'Alocação saudável; sem burnout; capacidade absorve picos moderados.',
  '80–90%.',
  'Sprint',
  'Por Squad, Profissional',
  'Capacity (Sprint Planning)',
  'Dados de capacidade por user'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  34,
  'Fator de Foco (Pontos Entregues/Capacidade)',
  'FF',
  'Downstream',
  'Fluxo/Capacidade',
  'Calibrar cadência e carga real.',
  'Calibrar cadência e carga real.',
  'FF = story points concluídos ÷ capacidade estimada da sprint',
  'Reduzir interrupções; ajustar carga; melhorar slicing; negociar débitos técnicos.',
  'Entrega consistente vs capacidade; metas atingidas com regularidade.',
  '0,7–0,85 estável.',
  'Sprint',
  'Por Squad',
  'Story Points; Sprint Capacity',
  'Somatórios por sprint'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  35,
  'Índice de Troca de Contexto',
  'CSI',
  'Downstream',
  'Produtividade',
  'Reduzir dispersão e perdas cognitivas.',
  'Reduzir dispersão e perdas cognitivas.',
  'CSI = média de itens tocados por dev por dia',
  'Consolidar demandas; janelas de foco; limitar ad‑hoc; classes de serviço e políticas.',
  'Pouca troca de contexto; foco alto; produtividade sustentável.',
  '≤ 2 itens/dia/dev.',
  'Semanal',
  'Por Squad, Profissional',
  'AssignedTo; Activity log',
  'Eventos de mudança/commits vinculados'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  36,
  'Taxa de Hotfix pós-Release',
  'HFR',
  'Downstream',
  'Qualidade/Operação',
  'Sinal de qualidade de release.',
  'Sinal de qualidade de release.',
  'HFR = hotfixes em ≤72h pós-release ÷ releases',
  'Endurecer gates; smoke/health pós‑deploy; canary; checklist de release; evitar ‘big bang’.',
  'Quase nenhum hotfix pós-release; qualidade de release alta; clientes impactados minimamente.',
  '< 10%.',
  'Mensal',
  'Por Serviço',
  'Deployments; Tags ‘hotfix’',
  'Relacionar release e PRs ‘hotfix’'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  37,
  'Cumprimento de SLA (Sustentação)',
  'SLA%',
  'Downstream',
  'Suporte/Operação',
  'Garantir tempo de resposta/solução.',
  'Garantir tempo de resposta/solução.',
  'SLA% = chamados dentro do SLA ÷ chamados fechados',
  'Ajustar triagem/filas; playbooks por severidade; automatizar respostas; reforçar plantão.',
  'SLAs cumpridos; satisfação do cliente melhora; menos escalonamentos.',
  '≥ 95% (P1), ≥ 90% (P2).',
  'Mensal',
  'Por Severidade/Canal',
  'Work Item ‘Support Request/Incident’ com prioridade e due date',
  'Comparar ResolvedDate com SLA Date'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  38,
  'Taxa de Bugs Encontrados por Cliente',
  'CFBR',
  'Downstream',
  'Qualidade',
  'Diminuir dependência de cliente como QA.',
  'Diminuir dependência de cliente como QA.',
  'CFBR = bugs reportados por clientes ÷ bugs totais',
  'Aumentar e2e/contrato; beta privado; QA exploratório; instrumentar logs; UX review.',
  'Raros bugs descobertos pelo cliente; QA interno efetivo; imagem preservada.',
  '< 20%.',
  'Mensal',
  'Por Produto',
  'Bug com origem ‘Customer/Prod’',
  'Campo ‘FoundIn’ ou Tag ‘Customer’'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  39,
  'Tempo até Triagem',
  'TTT',
  'Upstream',
  'Suporte/Descoberta',
  'Dar visibilidade e direcionamento rápido.',
  'Dar visibilidade e direcionamento rápido.',
  'TTT = primeiro toque (triagem) − criação do item',
  'Triagem diária com dono; automação de roteamento; SLAs; categorização; dashboards de entrada.',
  'Itens triados rápido; decisão e encaminhamento claros; menos filas de entrada.',
  '< 24h úteis.',
  'Semanal',
  'Por Tipo (Bug/Idea)',
  'History (Assigned/State changed to ‘Triaged’)',
  'Detecção do primeiro status ‘Triaged’'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  40,
  'Tempo da Primeira Resposta',
  'TFR',
  'Downstream',
  'Suporte',
  'Sinal de atendimento rápido.',
  'Sinal de atendimento rápido.',
  'TFR = primeiro comentário/atribuição − criação',
  'Modelos de resposta; roteamento por severidade; metas de resposta; bots de alerta; handoff claro.',
  'Resposta inicial ágil; cliente percebe presença; menor pressão sobre o time.',
  '< 4h úteis (P2–P3), imediato para P1.',
  'Semanal',
  'Por Severidade/Canal',
  'Discussion/History',
  'Diferença entre CreationDate e primeiro comment'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  41,
  'Entrega Líquida de Funcionalidades',
  'NFD',
  'Downstream',
  'Portfólio',
  'Medir valor líquido de entrega vs correção.',
  'Medir valor líquido de entrega vs correção.',
  'NFD = pontos de features entregues − pontos de retrabalho/hotfix',
  'Cortar retrabalho/hotfix; reforçar qualidade pré‑release; reavaliar portfólio; priorizar outcomes.',
  'Mais valor líquido entregue; correções não dominam o roadmap; progresso visível.',
  'Tendência positiva trimestre a trimestre.',
  'Mensal/Trimestral',
  'Por Produto',
  'Story Points, Tags ‘hotfix/rework’',
  'Somatórios por tipo/tag'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  42,
  'Taxa de Correção de Bugs',
  'BFR',
  'Downstream',
  'Qualidade',
  'Evitar backlog infinito de bugs.',
  'Evitar backlog infinito de bugs.',
  'BFR = bugs fechados ÷ bugs abertos no período',
  'Força‑tarefa de bugs; metas semanais; ‘um abre/um fecha’; evitar abrir sem repro; foco P1/P2.',
  'Estoque de bugs sob controle ou caindo; foco em severidades altas; sensação de limpeza.',
  '> 1,0 continuamente até estabilizar.',
  'Semanal',
  'Por Severidade/Produto',
  'Bug State open/closed',
  'Entradas vs saídas no período'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  43,
  'Lead Time de Mudanças (Commit→Prod)',
  'MLTC',
  'Downstream',
  'DevOps/DORA+',
  'Acelerar pipeline de ponta a ponta.',
  'Acelerar pipeline de ponta a ponta.',
  'MLTC = produção − primeiro commit incluído na release',
  'Automatizar CD; reduzir aprovações; PRs menores; build incremental; trunk‑based; release por commit.',
  'Pipeline do commit ao prod curto; mudanças chegam no mesmo dia; ciclo de feedback acelerado.',
  '< 1 dia para serviços core.',
  'Semanal',
  'Por Serviço/Repo',
  'Commits↔Builds↔Releases',
  'Correlacionar via artefatos do pipeline'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  44,
  'Tempo PR Merge → Deploy em Produção',
  'PR2DEP',
  'Downstream',
  'DevOps',
  'Reduzir lead time pós-merge.',
  'Reduzir lead time pós-merge.',
  'PR2DEP = deploy_prod − merge_time',
  'Deploy auto pós‑merge; revisar gates; pipelines por serviço; toggles para ativação gradual.',
  'Merge vai rápido para produção; menos ‘espera em staging’; integrações contínuas.',
  '< 12h.',
  'Semanal',
  'Por Serviço',
  'PRs; Deployments',
  'Join PRs merged com release contendo commit'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  45,
  'Distribuição de Origem de Defeitos',
  'DEF-ORIG',
  'Downstream',
  'Qualidade',
  'Atacar a etapa geradora de defeitos.',
  'Atacar a etapa geradora de defeitos.',
  '% por origem (Requisitos, Design, Código, Infra, Dados)',
  'Treinar origem dominante; testes de contrato; SLO por origem; checklists preventivos.',
  'Causas-raiz distribuídas; queda nas origens dominantes; prevenção funcionando.',
  'Queda de origens dominantes.',
  'Trimestral',
  'Por Produto',
  'Campo custom ‘Origin’ em Bug',
  'Distribuição por campo'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  46,
  'Tempo em Coluna ‘Review/QA’ (Mediana)',
  'TREV',
  'Downstream',
  'Fluxo/Teste',
  'Reduzir filas de QA/Review.',
  'Reduzir filas de QA/Review.',
  'Mediana do tempo na coluna de revisão',
  'Aumentar capacidade de review/QA; janela fixa; paralelizar testes; priorizar filas longas.',
  'Review/QA flui; filas pequenas; lançamento sem gargalos finais.',
  '< 1 dia.',
  'Semanal',
  'Por Squad',
  'Snapshots por coluna Kanban',
  'Duração por coluna'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  47,
  'Aging de Itens em Progresso (P80)',
  'AGING-WIP',
  'Downstream',
  'Fluxo',
  'Evitar ‘zumbis’ no fluxo.',
  'Evitar ‘zumbis’ no fluxo.',
  'P80 do tempo corrido em estado ‘In Progress’',
  'Daily de desbloqueio; swarming; renegociar prioridades; matar itens zumbis; limites de idade.',
  'Itens não envelhecem; sem ‘zumbis’; sinais de fluxo saudável.',
  'P80 < 4 dias.',
  'Diário/Semanal',
  'Por Squad, Profissional',
  'State duration',
  'Snapshots com dias no estado'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  48,
  'Taxa de Carregamento para Próxima Sprint',
  'CARRY%',
  'Downstream',
  'Planejamento',
  'Melhorar acurácia de planejamento.',
  'Melhorar acurácia de planejamento.',
  'CARRY% = itens não concluídos ÷ itens comprometidos',
  'Planejar com buffer; re‑slicing; defender foco; reduzir interrupções de sustentação; política de carryover.',
  'Pouco carryover; squads encerram o planejado; confiança no fechamento da sprint.',
  '< 15%.',
  'Sprint',
  'Por Squad',
  'Backlog/Iteration',
  'Comparar estado no fim da sprint'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  49,
  'Utilização Individual (Horas)',
  'UTIL/h',
  'Downstream',
  'Capacidade/Pessoas',
  'Evitar burnout e ociosidade.',
  'Evitar burnout e ociosidade.',
  'Horas logadas ou alocadas ÷ horas disponíveis',
  'Replanejar alocação; balancear demanda; monitorar burnout/férias; reduzir horas extras; automatizar repetitivos.',
  'Utilização sustentável; sem excesso de horas; moral e qualidade preservadas.',
  '70–85%.',
  'Semanal/Sprint',
  'Por Profissional',
  'Capacity; (se timesheet integrado)',
  'Capacity by user'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  50,
  'Carga de Fluxo (WIP total)',
  'FLOW/WIP',
  'Downstream',
  'Fluxo',
  'Manter WIP sob controle para acelerar fluxo.',
  'Manter WIP sob controle para acelerar fluxo.',
  'Qtde itens em estados ativos no momento',
  'Definir WIP por coluna; políticas Kanban; priorizar finalização; classes de serviço; gestão visual do fluxo.',
  'Quadro limpo; WIP dentro do limite; sistema responde rápido a novas demandas.',
  'WIP por coluna dentro do WIP limit.',
  'Diário',
  'Por Squad/Coluna',
  'Board states/columns',
  'Count por estado'
);

INSERT INTO public.indicators (
  is_active,
  is_kr,
  priority,
  name,
  acronym,
  type,
  category,
  description,
  objective,
  calculation_formula,
  action_when_bad,
  result_when_good,
  suggested_target,
  default_granularity,
  segmentation,
  azure_devops_source,
  base_query
) VALUES (
  true,
  false,
  0,
  'Adoção de IA',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
);

-- Total de indicadores inseridos: 51
-- Categorias únicas: Fluxo/Entrega, DevOps/DORA, Fluxo, Planejamento, Fluxo/Lean, Fluxo/Capacidade, Qualidade, Qualidade/Suporte, Qualidade/Fluxo, Qualidade/Processo, CI/CD, Qualidade/Testes, Qualidade/Código, Código/Fluxo, Processo, Discovery/Backlog, Qualidade de Especificação, Discovery/Produto, Discovery/Arquitetura, Portfólio/Balanceamento, Capacidade, Produtividade, Qualidade/Operação, Suporte/Operação, Suporte/Descoberta, Suporte, Portfólio, DevOps/DORA+, DevOps, Fluxo/Teste, Capacidade/Pessoas
